import { Montserrat } from 'next/font/google'
import './globals.css'
import Footer from "@/app/components/footer";
import Navbar from "@/app/components/navbar";

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Dinacom',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <Navbar/>
      {children}
      <Footer/>
      </body>

    </html>
  )
}
