import { Montserrat } from 'next/font/google'
import './globals.css'
import Dashboard from './dashboard/page'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Dinacom',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
        {montserrat.styles}
      </body>
    </html>
  )
}
